// ==UserScript==
// @name         Word Online IA Injector (100% Online)
// @namespace    https://github.com/Jose2011397/Word-AI-on-line
// @version      6.0.0
// @description  Injeta comandos de IA no Word Online chamando o servidor na nuvem
// @author       Jose2011397
// @match        https://*.officeapps.live.com/*
// @match        https://word.cloud.microsoft/*
// @match        https://word.office.com/*
// @match        https://*.office.com/*
// @updateURL    https://raw.githubusercontent.com/Jose2011397/Word-AI-on-line/main/extension/word-injector.user.js
// @downloadURL  https://raw.githubusercontent.com/Jose2011397/Word-AI-on-line/main/extension/word-injector.user.js
// @connect      SEU-APP-NO-RENDER.onrender.com
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// ==/UserScript==

(function() {
    'use strict';

        const API_URL = "https://SEU-APP-NO-RENDER.onrender.com/gerar";
            let processando = false;

                function exibirNotificacao(mensagem, erro = false) {
                        let toast = document.getElementById("ia-toast-notif");
                                if (!toast) {
                                            toast = document.createElement("div");
                                                        toast.id = "ia-toast-notif";
                                                                    toast.style.position = "fixed";
                                                                                toast.style.top = "15px";
                                                                                            toast.style.right = "15px";
                                                                                                        toast.style.zIndex = "999999";
                                                                                                                    toast.style.padding = "10px 16px";
                                                                                                                                toast.style.borderRadius = "8px";
                                                                                                                                            toast.style.fontSize = "14px";
                                                                                                                                                        toast.style.fontWeight = "bold";
                                                                                                                                                                    toast.style.color = "#fff";
                                                                                                                                                                                toast.style.boxShadow = "0 4px 12px rgba(0,0,0,0.3)";
                                                                                                                                                                                            toast.style.transition = "all 0.3s ease";
                                                                                                                                                                                                        document.body.appendChild(toast);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                        toast.style.backgroundColor = erro ? "#d9534f" : "#0078d4";
                                                                                                                                                                                                                                toast.innerText = mensagem;
                                                                                                                                                                                                                                        toast.style.display = "block";
                                                                                                                                                                                                                                                if (!erro) setTimeout(() => { toast.style.display = "none"; }, 3000);
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        function apagarComandoEInserir(tamanhoComando, resposta) {
                                                                                                                                                                                                                                                                const activeEl = document.activeElement;

                                                                                                                                                                                                                                                                        if (activeEl) {
                                                                                                                                                                                                                                                                                    for (let i = 0; i < tamanhoComando + 2; i++) {
                                                                                                                                                                                                                                                                                                    document.execCommand('delete', false, null);
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                            const textoFinal = resposta + "\n\n";
                                                                                                                                                                                                                                                                                                                                        const sucesso = document.execCommand('insertText', false, textoFinal);

                                                                                                                                                                                                                                                                                                                                                    if (!sucesso) {
                                                                                                                                                                                                                                                                                                                                                                    const event = new ClipboardEvent('paste', {
                                                                                                                                                                                                                                                                                                                                                                                        bubbles: true,
                                                                                                                                                                                                                                                                                                                                                                                                            cancelable: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                dataType: 'text/plain',
                                                                                                                                                                                                                                                                                                                                                                                                                                                    data: textoFinal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    activeEl.dispatchEvent(event);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function processarAposEnter() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (processando) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const textoPagina = document.body.innerText || "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const match = textoPagina.match(/\bIA:\s*(\*+)([^\*\n\r]+)(\*+)/i);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (match) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const asteriscosInicio = match[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const promptTexto = match[2].trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const asteriscosFim = match[3];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (asteriscosInicio.length !== asteriscosFim.length) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const qtdAsteriscos = asteriscosInicio.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const chavePedido = `${qtdAsteriscos}_${promptTexto.toLowerCase()}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const historico = JSON.parse(GM_getValue("historico_ia_word", "[]"));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (historico.includes(chavePedido)) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            processando = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const tamanhoParaApagar = match[0].length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    exibirNotificacao("🧠 Processando novo pedido...");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GM_xmlhttpRequest({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                url: API_URL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data: JSON.stringify({ prompt: promptTexto }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timeout: 35000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onload: function(response) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const res = JSON.parse(response.responseText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (res.resposta) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                historico.push(chavePedido);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            GM_setValue("historico_ia_word", JSON.stringify(historico));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        apagarComandoEInserir(tamanhoParaApagar, res.resposta);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    exibirNotificacao("✅ Concluído!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exibirNotificacao("❌ Erro: " + (res.erro || "Sem resposta"), true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            exibirNotificacao("❌ Erro no formato do texto", true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processando = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onerror: function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exibirNotificacao("❌ Falha na conexão com o servidor na nuvem", true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            processando = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.addEventListener('keyup', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const isEnter = e.key === 'Enter' || e.keyCode === 13 || e.which === 13 || e.keyCode === 229;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isEnter) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(processarAposEnter, 300);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })();