import os
import re
import requests
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
SPIDER_API_KEY = os.getenv("SPIDER_API_KEY", "")

def obter_modelo_groq():
    headers = {'Authorization': f'Bearer {GROQ_API_KEY}'}
        preferencias = [
                "llama-3.3-70b-versatile",
                        "llama-3.1-8b-instant",
                                "openai/gpt-oss-120b",
                                        "qwen/qwen3.8-27b"
                                            ]
                                                try:
                                                        res = requests.get('https://api.groq.com/openai/v1/models', headers=headers, timeout=10)
                                                                if res.status_code == 200:
                                                                            disponiveis = [m['id'] for m in res.json().get('data', [])]
                                                                                        for pref in preferencias:
                                                                                                        if pref in disponiveis:
                                                                                                                            return pref
                                                                                                                                        if disponiveis:
                                                                                                                                                        return disponiveis[0]
                                                                                                                                                            except Exception as e:
                                                                                                                                                                    print(f"[*] Erro ao buscar modelos Groq: {e}")
                                                                                                                                                                        return "llama-3.1-8b-instant"

                                                                                                                                                                        MODELO_ATIVO = obter_modelo_groq()

                                                                                                                                                                        def extrair_texto_spider(url):
                                                                                                                                                                            headers = {
                                                                                                                                                                                    'Authorization': f'Bearer {SPIDER_API_KEY}',
                                                                                                                                                                                            'Content-Type': 'application/json'
                                                                                                                                                                                                }
                                                                                                                                                                                                    try:
                                                                                                                                                                                                            res = requests.post(
                                                                                                                                                                                                                        'https://api.spider.cloud/v1/crawl', 
                                                                                                                                                                                                                                    headers=headers, 
                                                                                                                                                                                                                                                json={"url": url, "return_format": "markdown"}, 
                                                                                                                                                                                                                                                            timeout=15
                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                            if res.status_code == 200:
                                                                                                                                                                                                                                                                                        dados = res.json()
                                                                                                                                                                                                                                                                                                    return dados[0].get('content', '') if isinstance(dados, list) and dados else dados.get('content', '')
                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                print(f"[*] Erro Spider: {e}")
                                                                                                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                                                                                                    @app.route('/', methods=['GET'])
                                                                                                                                                                                                                                                                                                                    def home():
                                                                                                                                                                                                                                                                                                                        return jsonify({"status": "Servidor IA Online", "modelo": MODELO_ATIVO}), 200

                                                                                                                                                                                                                                                                                                                        @app.route('/gerar', methods=['POST'])
                                                                                                                                                                                                                                                                                                                        def gerar():
                                                                                                                                                                                                                                                                                                                            data = request.get_json()
                                                                                                                                                                                                                                                                                                                                prompt = data.get("prompt", "") if data else ""

                                                                                                                                                                                                                                                                                                                                    if not prompt:
                                                                                                                                                                                                                                                                                                                                            return jsonify({"erro": "Prompt vazio"}), 400

                                                                                                                                                                                                                                                                                                                                                url_match = re.search(r'https?://[^\s]+', prompt)
                                                                                                                                                                                                                                                                                                                                                    if url_match:
                                                                                                                                                                                                                                                                                                                                                            url = url_match.group(0)
                                                                                                                                                                                                                                                                                                                                                                    texto_site = extrair_texto_spider(url)
                                                                                                                                                                                                                                                                                                                                                                            if texto_site:
                                                                                                                                                                                                                                                                                                                                                                                        prompt = f"Instrução: {prompt}\n\nConteúdo da página:\n{texto_site}"

                                                                                                                                                                                                                                                                                                                                                                                            headers = {
                                                                                                                                                                                                                                                                                                                                                                                                    'Authorization': f'Bearer {GROQ_API_KEY}',
                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                        payload = {
                                                                                                                                                                                                                                                                                                                                                                                                                                "model": MODELO_ATIVO,
                                                                                                                                                                                                                                                                                                                                                                                                                                        "messages": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"role": "system", "content": "Você é um assistente útil e direto."},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {"role": "user", "content": prompt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "temperature": 0.7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res = requests.post("https://api.groq.com/openai/v1/chat/completions", headers=headers, json=payload, timeout=25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if res.status_code == 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resposta = res.json()["choices"][0]["message"]["content"].strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonify({"resposta": resposta})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonify({"erro": f"Erro na API ({res.status_code})"}), 500
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonify({"erro": str(e)}), 500

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    port = int(os.environ.get("PORT", 5000))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.run(host='0.0.0.0', port=port)